
package cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculaFatorial", targetNamespace = "http://control/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculaFatorial {


    /**
     * 
     * @param num
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fatorial", targetNamespace = "http://control/", className = "cliente.Fatorial")
    @ResponseWrapper(localName = "fatorialResponse", targetNamespace = "http://control/", className = "cliente.FatorialResponse")
    @Action(input = "http://control/CalculaFatorial/fatorialRequest", output = "http://control/CalculaFatorial/fatorialResponse")
    public int fatorial(
        @WebParam(name = "num", targetNamespace = "")
        int num);

}
